POST localhost:8080/api/tasks
Content-Type: application/json

{
"title": "Zrobić zadanie z modułu 2",
"description": "Coś dodane"
}

###

GET localhost:8080/api/tasks

###

GET localhost:8080/api/tasks/1

###

DELETE  localhost:8080/api/tasks/1

###

PUT localhost:8080/api/tasks/1
Content-Type: application/json

{
  "title": "Zrobić zadanie z modułu 3 po update",
  "description": "Coś dodane po update"
}

###